package content

const (
	ObjectParentAllEndpoint  = "/content/v2/object/parent/all"
	ObjectAllEndpoint        = "/content/v2/object/all"
	ObjectCharcsEndpoint     = "/content/v2/object/charcs/%d"
	ColorsEndpoint           = "/content/v2/directory/colors"
	KindsEndpoint            = "/content/v2/directory/kinds"
	CountriesEndpoint        = "/content/v2/directory/countries"
	SeasonsEndpoint          = "/content/v2/directory/seasons"
	VATEndpoint              = "/content/v2/directory/vat"
	TNVEDEndpoint            = "/content/v2/directory/tnved"
	BrandsEndpoint           = "/api/content/v1/brands"
	TagsEndpoint             = "/content/v2/tags"
	TagEndpoint              = "/content/v2/tag"
	TagByIDEndpoint          = "/content/v2/tag/%d"
	TagNomenclatureEndpoint  = "/content/v2/tag/nomenclature/link"
	GetCardsListEndpoint     = "/content/v2/get/cards/list"
	CardsErrorsListEndpoint  = "/content/v2/cards/error/list"
	CardsUpdateEndpoint      = "/content/v2/cards/update"
	CardsMoveNMEndpoint      = "/content/v2/cards/moveNm"
	CardsDeleteTrashEndpoint = "/content/v2/cards/delete/trash"
	CardsRecoverEndpoint     = "/content/v2/cards/recover"
	GetCardsTrashEndpoint    = "/content/v2/get/cards/trash"
	CardsLimitsEndpoint      = "/content/v2/cards/limits"
	BarcodesEndpoint         = "/content/v2/barcodes"
	CardsUploadEndpoint      = "/content/v2/cards/upload"
	CardsUploadAddEndpoint   = "/content/v2/cards/upload/add"
	MediaFileEndpoint        = "/content/v3/media/file"
	MediaSaveEndpoint        = "/content/v3/media/save"
)
